CAN:
    type: 1           # CAN_PEAK_USN
    path: /dev/pcan33
    baudrate: 0x0     # CANITFBAUD_1M

FTS:
    base_identifier: 0x20
    
node:
    ft_pub_freq: 650
    frame: "kms_real"
    transform_frame: "kms_transformed_link"
    
Calibration:
    n_measurements: 50
    T_between_meas: 10000
    
CoordinateSystemCal:
    n_measurements: 10
    T_between_meas: 10000
    push_direction: 0      # angle to +y (0 to +x)
