CAN:
    type: 1            # CAN_PEAK_USB
    path: /dev/pcan32
    baudrate: 0x04     # CANITFBAUD_250K

FTS:
    base_identifier: 0x20
    auto_init: true
    fts_name: "ATI_45_Mini"

node:
    ft_pub_freq: 650
    frame: "fts_reference_link"
    transform_frame: "fts_base_link"

Calibration:
    n_measurements: 500
    T_between_meas: 10000
