CAN:
    type: 1           # CAN_PEAK_USN
    path: /dev/pcan33
    baudrate: 0x04     # CANITFBAUD_1M

FTS:
    base_identifier: 0x20
    
node:
    ft_pub_freq: 650
    frame: "kms_real"
    transform_frame: "base_link"
    
Calibration:
    n_measurements: 500
    T_between_meas: 10000
    static: true # true= use static offset Calibration, false=use calibrate Sensor to 0 in current State
    offset_fx: -19.40 #-19.12 #20.05 #-19.81
    offset_fy: -2.31 #-0.67 #-3.38 #-5.44
    offset_fz: -3.52 #1.34 #-6.76 #-0.21    
    offset_mx: -0.185 #-0.153 #-0.241 #-0.294
    offset_my: 0.025 #0.066 #0.001 #-0.040
    offset_mz: 0.118 #0.110 #0.117 #0.151
    
    
    
CoordinateSystemCal:
    n_measurements: 10
    T_between_meas: 10000
    push_direction: 0      # angle to +y (0 to +x)
