CAN:
    type: 1            # CAN_PEAK_USB
    path: /dev/pcan32
    baudrate: 0x04     # CANITFBAUD_250K

FTS:
    base_identifier: 0x20

node:
    ft_pub_freq: 650
    frame: "kms_real"
    transform_frame: "base_link"

Calibration:
    n_measurements: 500
    T_between_meas: 10000
